# Generated by Django 4.1 on 2022-11-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KB',
            fields=[
                ('alias', models.JSONField(default=list, verbose_name='别名')),
                ('subject_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='id')),
                ('subject', models.CharField(max_length=50, verbose_name='名称')),
                ('type', models.JSONField(default=list, verbose_name='类型')),
                ('data', models.JSONField(default=list, verbose_name='数据')),
            ],
        ),
        migrations.DeleteModel(
            name='testModel',
        ),
    ]
