# Generated by Django 4.1 on 2022-11-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0003_alter_kb_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('test', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
            ],
        ),
    ]
