# Generated by Django 4.1 on 2022-11-19 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0004_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSet',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False, verbose_name='自增id')),
                ('segment_id', models.CharField(max_length=20, verbose_name='段序号')),
                ('text', models.CharField(max_length=100, verbose_name='原始文本')),
                ('entity', models.CharField(max_length=50, verbose_name='抽取出的实体')),
                ('entity_kb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temp.kb')),
            ],
        ),
        migrations.DeleteModel(
            name='test',
        ),
    ]
